[workspace]
members = []

# Global package attributes
[workspace.package]
authors = ["Sofair Contributors <info@sofair.io>"]
license = "MIT or Apache-2.0"
documentation = "https://github.com/SofairOfficial/sleppa"
homepage = "https://github.com/SofairOfficial/sleppa"
repository = "https://github.com/SofairOfficial/sleppa"
edition = "2021"
rust-version = "1.67"

[profile.release]
lto = true
codegen-units = 1
incremental = false

[profile.bench]
lto = true
codegen-units = 1
incremental = false
